# Generated by Django 5.2.12 on 2026-04-07 15:07

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import fairdm.db.fields
import fairdm_geo.vocabularies.cgi.geosciml
import fairdm_geo.vocabularies.odm2
import fairdm_geo.vocabularies.stratigraphy
import research_vocabs.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("research_vocabs", "0002_alter_concept_unique_together"),
        ("sample", "0005_alter_sample_options_alter_samplerelation_options_and_more"),
        ("stratigraphy", "0002_alter_stratigraphicunit_genesis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SamplingLocation",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "type",
                    research_vocabs.fields.ConceptField(
                        default="unknown",
                        help_text="The type of sampling location.",
                        max_length=33,
                        verbose_name="type",
                        vocabulary=fairdm_geo.vocabularies.odm2.SiteType,
                    ),
                ),
                (
                    "elevation_datum",
                    research_vocabs.fields.ConceptField(
                        default="MSL",
                        help_text="The reference point for the elevation measurement, such as Mean Sea Level (MSL).",
                        max_length=7,
                        verbose_name="elevation datum",
                        vocabulary=fairdm_geo.vocabularies.odm2.ElevationDatum,
                    ),
                ),
                (
                    "elevation",
                    fairdm.db.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="The site elevation in meters with reference to the specified elevation datum.",
                        null=True,
                        unit_choices=["m", "ft"],
                        verbose_name="elevation",
                    ),
                ),
            ],
            options={
                "verbose_name": "sampling location",
                "verbose_name_plural": "sampling locations",
                "abstract": False,
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Borehole",
            fields=[
                (
                    "samplinglocation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="fairdm_geo_sites.samplinglocation",
                    ),
                ),
                (
                    "azimuth",
                    fairdm.db.fields.QuantityField(
                        base_units="deg",
                        blank=True,
                        help_text="The horizontal angle relative to a reference direction.",
                        null=True,
                        unit_choices=["deg"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ],
                        verbose_name="azimuth",
                    ),
                ),
                (
                    "inclination",
                    fairdm.db.fields.QuantityField(
                        base_units="deg",
                        blank=True,
                        help_text="The vertical angle relative to the horizontal plane where 90 is true vertical.",
                        null=True,
                        unit_choices=["deg"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="inclination",
                    ),
                ),
                (
                    "length",
                    fairdm.db.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="The total length of the hole.",
                        null=True,
                        unit_choices=["m"],
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="hole length",
                    ),
                ),
                (
                    "top",
                    fairdm.db.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="The distance to the top of the vertical interval relative to the vertical datum.",
                        null=True,
                        unit_choices=["m"],
                        verbose_name="top",
                    ),
                ),
                (
                    "bottom",
                    fairdm.db.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="The distance to the bottom of the vertical interval relative to the vertical datum.",
                        null=True,
                        unit_choices=["m"],
                        verbose_name="bottom",
                    ),
                ),
                (
                    "vertical_depth",
                    fairdm.db.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="The total depth of the vertical interval, calculated as the absolute difference between the interval top and interval bottom.",
                        null=True,
                        unit_choices=["m"],
                        verbose_name="vertical depth",
                    ),
                ),
                (
                    "vertical_datum",
                    models.CharField(
                        choices=[("MSL", "Mean Sea Level")],
                        default="MSL",
                        help_text="The vertical datum used to determine depth measurements.",
                        max_length=255,
                        verbose_name="vertical datum",
                    ),
                ),
                (
                    "age",
                    research_vocabs.fields.ConceptManyToManyField(
                        blank=True,
                        help_text="The geologic age of the interval.",
                        related_name="+",
                        to="research_vocabs.concept",
                        verbose_name="geologic age",
                        vocabulary=fairdm_geo.vocabularies.stratigraphy.GeologicalTimescale,
                    ),
                ),
                (
                    "lithology",
                    research_vocabs.fields.ConceptManyToManyField(
                        blank=True,
                        help_text="The lithology of the interval.",
                        related_name="+",
                        to="research_vocabs.concept",
                        verbose_name="lithology",
                        vocabulary=fairdm_geo.vocabularies.cgi.geosciml.SimpleLithology,
                    ),
                ),
                (
                    "stratigraphy",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The stratigraphy of the interval.",
                        to="stratigraphy.stratigraphicunit",
                        verbose_name="stratigraphy",
                    ),
                ),
            ],
            options={
                "verbose_name": "borehole",
                "verbose_name_plural": "boreholes",
                "abstract": False,
            },
            bases=("fairdm_geo_sites.samplinglocation", models.Model),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
