# Generated by Django 5.0.8 on 2024-09-20 08:40

import research_vocabs.fields
from django.db import migrations, models

import fairdm_geo.vocabularies.cgi.geosciml


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StratigraphicUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    research_vocabs.fields.ConceptField(
                        blank=True,
                        max_length=18,
                        null=True,
                        verbose_name="Stratigraphic Rank",
                        vocabulary=fairdm_geo.vocabularies.cgi.geosciml.StratigraphicRank,
                    ),
                ),
                (
                    "genesis",
                    research_vocabs.fields.ConceptField(
                        blank=True,
                        max_length=47,
                        null=True,
                        verbose_name="Genetic Category",
                        vocabulary=fairdm_geo.vocabularies.cgi.geosciml.GeneticCategory,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stratigraphic Unit",
                "verbose_name_plural": "Stratigraphic Units",
            },
        ),
    ]
