# Generated by Django 5.1.3 on 2025-02-11 08:50

import fairdm_geo.vocabularies.cgi.geosciml
import research_vocabs.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stratigraphy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stratigraphicunit",
            name="genesis",
            field=research_vocabs.fields.ConceptField(
                blank=True,
                max_length=47,
                null=True,
                verbose_name="Genetic Category",
                vocabulary=fairdm_geo.vocabularies.cgi.geosciml.GeneticCategory,
            ),
        ),
        migrations.AlterField(
            model_name="stratigraphicunit",
            name="rank",
            field=research_vocabs.fields.ConceptField(
                blank=True,
                max_length=18,
                null=True,
                verbose_name="Stratigraphic Rank",
                vocabulary=fairdm_geo.vocabularies.cgi.geosciml.StratigraphicRank,
            ),
        ),
    ]
