# Generated by Django 5.2.12 on 2026-04-07 15:08

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fairdm_geo_sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericSite",
            fields=[
                (
                    "samplinglocation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="fairdm_geo_sites.samplinglocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generic Site",
                "verbose_name_plural": "Generic Sites",
                "abstract": False,
            },
            bases=("fairdm_geo_sites.samplinglocation",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
