# Generated by Django 5.1.6 on 2025-02-20 14:01

import django.db.models.deletion
import fairdm.db.fields
import fairdm_geo.vocabularies.odm2
import research_vocabs.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fairdm_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericSite",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="fairdm_core.sample",
                    ),
                ),
                (
                    "type",
                    research_vocabs.fields.ConceptField(
                        default="unknown",
                        help_text="The type of sampling location.",
                        max_length=33,
                        verbose_name="type",
                        vocabulary=fairdm_geo.vocabularies.odm2.SiteType,
                    ),
                ),
                (
                    "elevation_datum",
                    research_vocabs.fields.ConceptField(
                        default="MSL",
                        max_length=7,
                        verbose_name="",
                        vocabulary=fairdm_geo.vocabularies.odm2.ElevationDatum,
                    ),
                ),
                (
                    "elevation",
                    fairdm.db.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="The site elevation in meters with reference to the specified elevation datum.",
                        null=True,
                        unit_choices=["m", "ft"],
                        verbose_name="elevation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generic Site",
                "verbose_name_plural": "Generic Sites",
                "abstract": False,
            },
            bases=("fairdm_core.sample",),
        ),
    ]
