# Generated by Django 5.0.7 on 2024-08-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeologicalTimescale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vocab_name",
                    models.CharField(max_length=255, verbose_name="vocabulary"),
                ),
                ("uri", models.URLField(unique=True, verbose_name="URI")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "label",
                    models.CharField(max_length=255, verbose_name="preferred label"),
                ),
                (
                    "older_bound",
                    models.FloatField(
                        blank=True, null=True, verbose_name="older bound"
                    ),
                ),
                (
                    "older_bound_uncertainty",
                    models.FloatField(
                        blank=True, null=True, verbose_name="older bound uncertainty"
                    ),
                ),
                (
                    "younger_bound",
                    models.FloatField(
                        blank=True, null=True, verbose_name="younger bound"
                    ),
                ),
                (
                    "younger_bound_uncertainty",
                    models.FloatField(
                        blank=True, null=True, verbose_name="lower bound uncertainty"
                    ),
                ),
            ],
            options={
                "verbose_name": "Geological Era",
                "verbose_name_plural": "Geological Eras",
            },
        ),
    ]
