# Generated by Django 5.0.8 on 2024-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geologic_time", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geologicaltimescale",
            name="id",
        ),
        migrations.AlterField(
            model_name="geologicaltimescale",
            name="name",
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name="name"),
        ),
    ]
