# Generated by Django 5.1.6 on 2025-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geologic_time", "0002_remove_geologicaltimescale_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geologicaltimescale",
            name="meta",
            field=models.JSONField(
                blank=True,
                help_text="Additional metadata about the concept, such as synonyms, definitions, etc.",
                null=True,
                verbose_name="metadata",
            ),
        ),
    ]
