# Generated by Django 5.2.12 on 2026-04-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geologic_time", "0003_geologicaltimescale_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geologicaltimescale",
            name="vocab_name",
        ),
    ]
