# Generated by Django 5.0.8 on 2024-09-03 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lithology", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplelithology",
            options={
                "verbose_name": "Simple Lithology",
                "verbose_name_plural": "Simple Lithology",
            },
        ),
    ]
