# Generated by Django 5.1.6 on 2025-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lithology", "0003_remove_simplelithology_id_alter_simplelithology_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplelithology",
            name="meta",
            field=models.JSONField(
                blank=True,
                help_text="Additional metadata about the concept, such as synonyms, definitions, etc.",
                null=True,
                verbose_name="metadata",
            ),
        ),
    ]
