# Generated by Django 5.2.12 on 2026-04-07 15:07

import django.db.models.deletion
import django.db.models.manager
import fairdm_geo.vocabularies.odm2
import research_vocabs.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sample", "0005_alter_sample_options_alter_samplerelation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrillCore",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "feature_type",
                    research_vocabs.fields.ConceptField(
                        default="specimen",
                        editable=False,
                        max_length=28,
                        verbose_name="",
                        vocabulary=fairdm_geo.vocabularies.odm2.SamplingFeatureType,
                    ),
                ),
                (
                    "medium",
                    research_vocabs.fields.ConceptField(
                        default="rock",
                        editable=False,
                        max_length=13,
                        verbose_name="medium",
                        vocabulary=fairdm_geo.vocabularies.odm2.Medium,
                    ),
                ),
                (
                    "specimen_type",
                    research_vocabs.fields.ConceptField(
                        default="core",
                        max_length=25,
                        verbose_name="specimen",
                        vocabulary=fairdm_geo.vocabularies.odm2.SpecimenType,
                    ),
                ),
            ],
            options={
                "verbose_name": "drill core",
                "verbose_name_plural": "drill cores",
                "abstract": False,
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DrillCuttings",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "feature_type",
                    research_vocabs.fields.ConceptField(
                        default="specimen",
                        editable=False,
                        max_length=28,
                        verbose_name="",
                        vocabulary=fairdm_geo.vocabularies.odm2.SamplingFeatureType,
                    ),
                ),
                (
                    "medium",
                    research_vocabs.fields.ConceptField(
                        default="rock",
                        editable=False,
                        max_length=13,
                        verbose_name="medium",
                        vocabulary=fairdm_geo.vocabularies.odm2.Medium,
                    ),
                ),
                (
                    "specimen_type",
                    research_vocabs.fields.ConceptField(
                        default="cuttings",
                        editable=False,
                        max_length=25,
                        verbose_name="specimen",
                        vocabulary=fairdm_geo.vocabularies.odm2.SpecimenType,
                    ),
                ),
            ],
            options={
                "verbose_name": "drill cuttings",
                "verbose_name_plural": "drill cuttings",
                "abstract": False,
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="RockPowder",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "feature_type",
                    research_vocabs.fields.ConceptField(
                        default="specimen",
                        editable=False,
                        max_length=28,
                        verbose_name="",
                        vocabulary=fairdm_geo.vocabularies.odm2.SamplingFeatureType,
                    ),
                ),
                (
                    "medium",
                    research_vocabs.fields.ConceptField(
                        default="rock",
                        editable=False,
                        max_length=13,
                        verbose_name="medium",
                        vocabulary=fairdm_geo.vocabularies.odm2.Medium,
                    ),
                ),
                (
                    "specimen_type",
                    research_vocabs.fields.ConceptField(
                        default="powder",
                        editable=False,
                        max_length=25,
                        verbose_name="specimen",
                        vocabulary=fairdm_geo.vocabularies.odm2.SpecimenType,
                    ),
                ),
            ],
            options={
                "verbose_name": "rock powder",
                "verbose_name_plural": "rock powders",
                "abstract": False,
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="RockSample",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "feature_type",
                    research_vocabs.fields.ConceptField(
                        default="specimen",
                        editable=False,
                        max_length=28,
                        verbose_name="",
                        vocabulary=fairdm_geo.vocabularies.odm2.SamplingFeatureType,
                    ),
                ),
                (
                    "medium",
                    research_vocabs.fields.ConceptField(
                        default="rock",
                        editable=False,
                        max_length=13,
                        verbose_name="medium",
                        vocabulary=fairdm_geo.vocabularies.odm2.Medium,
                    ),
                ),
                (
                    "specimen_type",
                    research_vocabs.fields.ConceptField(
                        default="individualSample",
                        editable=False,
                        max_length=25,
                        verbose_name="specimen",
                        vocabulary=fairdm_geo.vocabularies.odm2.SpecimenType,
                    ),
                ),
            ],
            options={
                "verbose_name": "rock sample",
                "verbose_name_plural": "rock samples",
                "abstract": False,
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ThinSection",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "feature_type",
                    research_vocabs.fields.ConceptField(
                        default="specimen",
                        editable=False,
                        max_length=28,
                        verbose_name="",
                        vocabulary=fairdm_geo.vocabularies.odm2.SamplingFeatureType,
                    ),
                ),
                (
                    "medium",
                    research_vocabs.fields.ConceptField(
                        default="rock",
                        editable=False,
                        max_length=13,
                        verbose_name="medium",
                        vocabulary=fairdm_geo.vocabularies.odm2.Medium,
                    ),
                ),
                (
                    "specimen_type",
                    research_vocabs.fields.ConceptField(
                        default="thinSection",
                        editable=False,
                        max_length=25,
                        verbose_name="specimen",
                        vocabulary=fairdm_geo.vocabularies.odm2.SpecimenType,
                    ),
                ),
            ],
            options={
                "verbose_name": "thin section",
                "verbose_name_plural": "thin sections",
                "abstract": False,
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
